name: Build and Deploy to Harbor

on:
    push:
        branches: [main, master]
    workflow_dispatch:

env:
    REGISTRY: https://hub.rahona.app:8443
    IMAGE_NAME: salaunes-country-dans-backend

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Harbor Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}

            - name: Build Docker Image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.ref_name }} .

            - name: Tag Docker Image
              run: docker tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

            - name: Push Docker Image
              run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
